### ISSUE TITLE
Preprocessing reads

### ISSUE THREAD

**Issue by lalalagartija** [bachev/mira#11]
Hi, 

I am new to MIRA and I struggle to understand the docs. 
I am trying to follow the de novo RNAseq assembly pipeline but I fail just to preprocess reads as in the [doc 6.5.2](https://mira-assembler.sourceforge.net/docs/DefinitiveGuideToMIRA.html#chap_est). 
This is my manifest file : 
`project = De_novo_MIRA_Vir
job=est,denovo,accurate

readgroup
technology=solexa
autopairing
data=../data/A_1h_viralRaw_1.fastq ../data/A_1h_viralRaw_2.fastq
parameters = -AS:ppo=yes`

This is the error I get : 
`
========================= Parameter parsing error(s) ==========================

* Parameter section: '-AS'
*	unrecognised string or unexpected character: ppo

* Parameter section: '-AS'
*	unrecognised string or unexpected character: yes
*	(may be due to previous errors)

===============================================================================

Fatal error (may be due to problems of the input data or parameters):
`

I am sure it is something easy that I did not get. 

Thank you very much for your help

**Comment by DrMicrobit** [comment]
Yeah, ppo belongs to GENERAL, not ASSEMBLY :-)

-GE:ppo=yes
