### ISSUE TITLE
Are binaries available?

### ISSUE THREAD

**Issue by tnn111** [bachev/mira#2]
Are there any Darwin binaries available? Thanks.

**Comment by DrMicrobit** [comment]
Sorry, no. Apple kept breaking my build pipeline, I gave up some time ago. 

On July 26, 2019 7:33:28 PM GMT+02:00, tnn111 <notifications@github.com> wrote:
>Are there any Darwin binaries available? Thanks.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bachev/mira/issues/2

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
